swagger: "2.0"
info:
  title: Sample API
  description: API description in Markdown.
  version: 1.0.0
host: api.example.com
schemes:
  - https
paths:

  /users:
    post:
      summary: This is to crate new user
      operationId:
      parameters:
        -
      responses:

    get:
      summary: Returns a list of users.
      description: Optional extended description in Markdown.
      produces:
        - application/json
      parameters:
        - name
        - type: string
      responses:
        200:
          description: OK
